### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by gonzalonaveira** [plotly/react-plotly.js-demo-app#1]
Just cloned the repo and after npm install && npm start I'm getting:

`
Failed to compile
./src/components/ReactJSONEditor.react.js
Module not found: Can't resolve 'lodash.clonedeep' in '/Users/gonzalonaveira/Workspace/react-plotly.js-demo-app/src/components'
This error occurred during the build time and cannot be dismissed.
`

Tried adding lodash to the package.json:

`npm i --save lodash`

But no luck. Any idea?

**Comment by johndpope** [comment]
this didn't help 
https://github.com/gajus/react-css-modules/issues/239
npm i -D lodash
npm remove webpack
npm install webpack@3.11.0

**Comment by johndpope** [comment]
trying this repo instead - https://github.com/plotly/react-pivottable

**Comment by dmt0** [comment]
Workaround for now is:
```
npm install --save lodash.isequal
npm install --save lodash.clonedeep
```
